In [41]:
# Массивы numpy
# Функции для создания массивов numpy

In [5]:
import numpy as np

In [6]:
my_list = [1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_list

[1, 2, 3]

In [9]:
my_arr = np.array(my_list)

In [10]:
my_arr

array([1, 2, 3])

In [11]:
type(my_arr)

numpy.ndarray

In [12]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0, 10)  # аналог range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0, 101, 20) 

array([  0,  20,  40,  60,  80, 100])

In [22]:
np.zeros(shape=5)  # Создание одномерного массива из нулей, тип по умолчанию float

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2, 5))  # Количество строк и кооличество колонок

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((4, 4))  # Создание 4-мероного массива из единиц

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.linspace(0, 10, 50)  # Функция возвращает набор равноотстоящих друг от 
# друга чисел в указанном диапазоне (начало. конец, количестов чисел которые нужно вернуть внутри указанного диапазона).
# Конечная точка диапазона включена в результат!

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
np.linspace(0, 10, 3)  # Расстояние между числами одинаковое

array([ 0.,  5., 10.])

In [33]:
np.linspace(0, 10, 11)  # Верхняя граница включена в диапазон (10)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [36]:
np.linspace(0, 5, 21)  # Шаг = 0.25

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [37]:
len(np.linspace(0, 5, 21))

21

In [40]:
np.eye(5)  # Создает единичную матрицу в которой на главной диагонали находятся единицы, а в остальных ячейках нули
# Единичная матрица - это всегда квадратная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# Рассмотрим как создать случайное распределение чисел

In [44]:
np.random.rand()  # Указываем размерность массива и на выходе получаем массив с числами из 
# равномерного распределения от 0 до 1 (0 включается, 1 нет). Исп. равномерное распределение

0.8732151178971181

In [48]:
np.random.rand(1)  # одномерный массив

array([0.65986997])

In [54]:
np.random.rand(5, 2)  # 5 строк и 2 колонки. Диапазон от 0 до 1. Вероятность отдельных чисел одинакова

array([[0.33348716, 0.62272926],
       [0.39752414, 0.25127986],
       [0.85809048, 0.3050974 ],
       [0.1647022 , 0.4840282 ],
       [0.78919273, 0.79526757]])

In [55]:
# Распределение Гауса, стандартное нормальное распределение в котором мат. ожидание равно 0, а диспресия = 1

In [56]:
np.random.randn()  # Поскольку мат. ожидание = 0, то эта функция может возвращать как положительные так и отрицательные числа

0.33627079828467665

In [57]:
np.random.randn(10)

array([ 0.00725418, -0.13759019,  0.75699902, -0.43710684,  1.74310221,
        1.4338954 ,  0.46465576, -0.75843277,  0.84323158, -0.92136834])

In [58]:
np.random.randn(2, 3) # Чем ближе число к 0, тем больше вероятность получить его.

array([[-0.24083799, -0.31727586,  0.84433466],
       [ 0.75745664,  0.93951129,  0.65927495]])

In [68]:
np.random.randint(5, 20)  # Целые случайные числа. Исп. равномерное случайное распределение 
# и это будут  целые числа (), верхняя граница не включается

16

In [71]:
np.random.randint(5, 101, 25)  # Начало, конец, количество чисел

array([87, 19, 78, 16, 19, 97, 31, 14, 22, 91, 13,  8, 29, 16, 85, 94, 70,
       63, 19, 88, 26, 14, 97, 34, 51])

In [77]:
np.random.randint(5, 6, 25)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5])

In [78]:
# np.random.randint(5, 5, 25)  # ValueError: low >= high

In [80]:
np.random.randint(0, 101, (4, 5))  # Числа от 0 до 100 в 4 строках и 5 колонках

array([[27, 75, 34, 23, 53],
       [71, 79, 32, 87, 75],
       [20, 70,  2,  9, 98],
       [19, 38, 73, 55, 24]])

In [86]:
# Как сделать случайные результаты воспроиводимыми? 
np.random.seed(42)  # Эти две функции должны вызываться в одной ячейке
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [88]:
np.random.rand(4)  # Значения другие

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [90]:
arr = np.arange(0, 25)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [93]:
arr.reshape(5, 5)  # Получаем теже самые числа, но отформатированные в виде матрицы

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
# arr.reshape(5, 6)  # ValueError: cannot reshape array of size 25 into shape (5,6)

In [98]:
ranarr = np.random.randint(0, 101, 10)

In [99]:
ranarr

array([29, 37,  1, 63, 59, 20, 32, 75, 57, 21])

In [100]:
ranarr.max()

75

In [101]:
ranarr.min()

1

In [103]:
ranarr.argmax()  # Индекс масимального числа

7

In [105]:
ranarr.argmin()  # Индекс минимального числа

2

In [107]:
ranarr.dtype  # Тип данных в массиве и ихх размерность

dtype('int32')

In [108]:
ranarr.shape  # Размер или форма массива

(10,)

In [109]:
arr.shape

(25,)

In [110]:
arr = arr.reshape(5, 5)

In [111]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
arr.shape

(5, 5)

In [114]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [115]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [116]:
# Индексация и выборка

In [117]:
arr = np.arange(0, 11)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr[0]  # Получение по индексу

0

In [122]:
arr[1:5]  # Срез

array([1, 2, 3, 4])

In [123]:
arr[:5]

array([0, 1, 2, 3, 4])

In [124]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
# broadcast 
# Массивы в numpy отличаются от списков тем, что в них есть broadcast

In [130]:
arr[0:5] = 100  # В списках ошибка

In [129]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [131]:
# Операция присвоения нового значения сразу нескольким элементам называется broadcasting

In [132]:
arr = np.arange(0, 11)

In [133]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
slice_of_array = arr[0:5]  # Создается ссылка на эти элементы

In [135]:
slice_of_array

array([0, 1, 2, 3, 4])

In [139]:
slice_of_array[0] is arr[0]

False

In [140]:
id(slice_of_array[0])

1923590981104

In [141]:
id(arr[0])

1923590980976

In [142]:
slice_of_array[:] = 99

In [143]:
slice_of_array

array([99, 99, 99, 99, 99])

In [144]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [146]:
# Когда делали slice_of_array мы создали ссылки, а не копии этих элементов

In [148]:
# Если не хотим влиять на элементы исходного массива и создать копию, то это нужно сделать явно
arr_copy = arr.copy()

In [149]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [150]:
arr_copy[:] = 100

In [151]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [152]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [155]:
# Переходим к матрицам
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [156]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [158]:
arr_2d.shape  # (3, 3) - (количество строк, количество колонок)

(3, 3)

In [161]:
arr_2d[0]  # Первая строка массива

array([ 5, 10, 15])

In [162]:
arr_2d[-1]  # Вторая строка массива

array([35, 40, 45])

In [164]:
arr_2d[1][1]

25

In [165]:
arr_2d[1, 1]

25

In [166]:
# arr_2d[1][1] = arr_2d[1, 1]

In [167]:
arr_2d[0, -1]

15

In [168]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [169]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [188]:
# Выбор по условию (Conditional selection)

In [171]:
arr = np.arange(1, 11)

In [172]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
arr > 4  # Проверка всех элементов этого массива на условие больше 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [175]:
bool_array = arr > 4

In [176]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [178]:
arr[bool_array]  # Фильтрация массива по условию выше

array([ 5,  6,  7,  8,  9, 10])

In [187]:
arr = np.arange(1, 11)
arr[arr > 4]  # Такое тоже возможно, частый случай

array([ 5,  6,  7,  8,  9, 10])

In [190]:
# Операции с массивами numpy, эти операции позже можно применять и в pandas

In [191]:
arr = np.arange(0, 10)

In [192]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
arr + 5 # numpy прибавит 5 отдельно к каждому элементу массива

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [197]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [198]:
arr + arr  # При сложении массивов эти массивы должны быть одинакового размера

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [199]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [200]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [201]:
# При операции деления на 0, вместо ошибки получите предупреждение

In [202]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
arr / arr  # В 0 идексе получим значения nan (not a number)

C:\Users\dior\AppData\Local\Temp\ipykernel_11540\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [207]:
# 1 / 0  # ZeroDivisionError: division by zero, тут уже обычный питон

In [208]:
1 / arr  # Получим значение inf - бесконечность

C:\Users\dior\AppData\Local\Temp\ipykernel_11540\2030307195.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr  # Получим значение inf - бесконечность


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [210]:
np.sqrt(arr)  # sqrt применяется к каждму элементу массива

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [211]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [212]:
np.log(arr)

C:\Users\dior\AppData\Local\Temp\ipykernel_11540\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [216]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [218]:
arr.sum()

45

In [219]:
arr.mean()  # среднее значение

4.5

In [222]:
arr.var()  # Дисперсия

8.25

In [223]:
arr.std()  # Среднее квадратичное отклонение

2.8722813232690143

In [229]:
arr[:3], arr[:3].sum()  # Кортеж из двух элементов

(array([0, 1, 2]), 3)

In [232]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [233]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [234]:
arr_2d.shape

(5, 5)

In [239]:
arr_2d.sum()  # Сумма всех элементов матрицы

300

In [243]:
arr_2d.sum(axis=0)  # Сумма колонок eg 0+5+10+15+20

array([50, 55, 60, 65, 70])

In [244]:
arr_2d.sum(axis=1)  # сумма строк 0+1+2+3+4

array([ 10,  35,  60,  85, 110])